version: '3.9'
services:
  db:  
    container_name: timbra-db
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      
  adminer:
    container_name: timbra-db-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rest-api:
    container_name: timbra-rest-api 
    network_mode: host
    build: ./RestAPI
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
  
  